//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPlatform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalPlatform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By logging in, I agree to DigitalPlatform&apos;s.
        /// </summary>
        internal static string AgreeWithLoginTermsOfService {
            get {
                return ResourceManager.GetString("AgreeWithLoginTermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up, I agree to DigitalPlatform&apos;s .
        /// </summary>
        internal static string AgreeWithTermsOfService {
            get {
                return ResourceManager.GetString("AgreeWithTermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalPlatform.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        internal static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?(&quot;&quot;)(&quot;&quot;.+?(?&lt;!\\)&quot;&quot;@)|(([0-9A-z]((\.(?!\.))|[-!#\$%&amp;&apos;\*\+/=\?\^`\{\}\|~\w])*)(?&lt;=[0-9A-z])@))(?(\[)(\[(\d{1,3}\.){3}\d{1,3}\])|(([0-9A-z][-\w]*[0-9A-z]*\.)+[A-z][\-A-z]{0,4}[A-z]))$.
        /// </summary>
        internal static string EmailAddressPolicy {
            get {
                return ResourceManager.GetString("EmailAddressPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Facebook.
        /// </summary>
        internal static string FacebookButtonText {
            get {
                return ResourceManager.GetString("FacebookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Google.
        /// </summary>
        internal static string GoogleButtonText {
            get {
                return ResourceManager.GetString("GoogleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has invalid format..
        /// </summary>
        internal static string InvalidEmailAddressError {
            get {
                return ResourceManager.GetString("InvalidEmailAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first name cannot be empty..
        /// </summary>
        internal static string InvalidFirstNameError {
            get {
                return ResourceManager.GetString("InvalidFirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input format, it failed regex validation..
        /// </summary>
        internal static string InvalidInputErrorMessage {
            get {
                return ResourceManager.GetString("InvalidInputErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last name cannot be empty..
        /// </summary>
        internal static string InvalidLastNameError {
            get {
                return ResourceManager.GetString("InvalidLastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain: 8 to 16 characters, Upper and lowercase letters, At least one number and at least one non-alphabetical character (Not including &apos;.&apos;, &apos;,&apos; and &apos;~&apos;).
        /// </summary>
        internal static string InvalidPasswordError {
            get {
                return ResourceManager.GetString("InvalidPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number must contain 10 digits..
        /// </summary>
        internal static string InvalidPhoneNumberError {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must not be null, empty nor white space..
        /// </summary>
        internal static string NullOrWhiteSpaceValidationErrorMessage {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#\$%\^&amp;\*]).{8,16}$.
        /// </summary>
        internal static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([0-9]{10})$.
        /// </summary>
        internal static string PhoneNumberPolicy {
            get {
                return ResourceManager.GetString("PhoneNumberPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalPlatform.
        /// </summary>
        internal static string StartPageTitle {
            get {
                return ResourceManager.GetString("StartPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string TermsOfServiceLabel {
            get {
                return ResourceManager.GetString("TermsOfServiceLabel", resourceCulture);
            }
        }
    }
}
